"""xp and plant progression refactor

Revision ID: f4e5312f0182
Revises: 
Create Date: 2026-03-19 15:51:13.365628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4e5312f0182'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_types', sa.Column('growth_target_xp', sa.Integer(), nullable=True))
    op.add_column('plant_types', sa.Column('unlock_account_xp', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE plant_types
        SET growth_target_xp = COALESCE(
            seed_to_sprout_xp + sprout_to_small_plant_xp + small_plant_to_mature_plant_xp,
            500
        ),
            unlock_account_xp = 0
        """
    )
    op.alter_column('plant_types', 'growth_target_xp', nullable=False)
    op.alter_column('plant_types', 'unlock_account_xp', nullable=False)
    op.drop_column('plant_types', 'sprout_to_small_plant_xp')
    op.drop_column('plant_types', 'seed_to_sprout_xp')
    op.drop_column('plant_types', 'small_plant_to_mature_plant_xp')
    op.add_column('plants', sa.Column('plant_xp', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE plants SET plant_xp = 0, is_active = true WHERE plant_xp IS NULL OR is_active IS NULL")
    op.alter_column('plants', 'plant_xp', nullable=False)
    op.alter_column('plants', 'is_active', nullable=False)
    op.alter_column('plants', 'stage',
               existing_type=postgresql.ENUM('seed', 'sprout', 'small_plant', 'mature_plant', name='plantstage'),
               nullable=False)
    op.create_index('uq_plants_user_active', 'plants', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.add_column('users', sa.Column('account_xp', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET account_xp = COALESCE(xp, 0)")
    op.alter_column('users', 'account_xp', nullable=False)
    op.drop_column('users', 'xp')
    op.drop_column('users', 'streak_current')
    op.drop_column('users', 'streak_longest')
    op.drop_column('users', 'last_session_date')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_session_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_longest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_current', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'account_xp')
    op.drop_index('uq_plants_user_active', table_name='plants', postgresql_where=sa.text('is_active = true'))
    op.alter_column('plants', 'stage',
               existing_type=postgresql.ENUM('seed', 'sprout', 'small_plant', 'mature_plant', name='plantstage'),
               nullable=True)
    op.drop_column('plants', 'completed_at')
    op.drop_column('plants', 'is_active')
    op.drop_column('plants', 'plant_xp')
    op.add_column('plant_types', sa.Column('small_plant_to_mature_plant_xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant_types', sa.Column('seed_to_sprout_xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant_types', sa.Column('sprout_to_small_plant_xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('plant_types', 'unlock_account_xp')
    op.drop_column('plant_types', 'growth_target_xp')
    # ### end Alembic commands ###
